### PR TITLE
Passing args from SagemakerCommunicator to boto3

### PR DESCRIPTION
**Pull request by swappysh**

### CODE REVIEW

**Comment by swappysh** [comment]
Addressing #15

**Comment by swappysh** [comment]
Use case:

> SagemakerCommunicator(endpoint_name=<endpoint>, region="aws-region")

**Comment by swappysh** [comment]
@iacolippo can you review this small change

**Comment by iacolippo** [comment]
Hi @swappysh thank you for your patience. Do you see any other use case than passing the region?

If that is the only use case I would prefer to explicitly implement a `region` argument instead of generic `*args` and `**kwargs` but maybe I am missing something.

**Comment by iacolippo** [comment]
You can now provide the `region_name` to the [`SagemakerCommunicator`](https://github.com/lightonai/paradigm-client/blob/main/paradigm_client/communicator.py#L142C58-L142C58)

**Pull request closed without merging**
