### PR TITLE
Dev fix api key

### PR DESCRIPTION
**Pull request by famoreau**

### CODE REVIEW

**Comment by iacolippo** [comment]
Not sure this will work when using Sagemaker Inference Endpoints: we won't be able to instantiate a RemoteModel if we don't have an API key, but we don't need one for Sagemaker.

Intended behavior is:
- Sagemaker: auth is done through AWS account/env vars
- API: auth is done with API key

**Comment by famoreau** [comment]
> Intended behavior is:
>  - Sagemaker: auth is done through AWS account/env vars
>  - API: auth is done with API key

Can I filter this behavior based on the given communicator when init a `RemoteModel` ?
 - If the `comm` parameter is `None` or a standard `paradigm-client.communicator.Communicator`:
Raises an assertion error if there is no `PARADIGM_API_KEY` env variable or no given `api_key` value.
 - If the `comm` parameter is of type `paradigm-client.communicator.SagemakerCommunicator`:
Do not check for an api key.

**Comment by iacolippo** [comment]
> Can I filter this behavior based on the given communicator when init a `RemoteModel` ?
> 
> * If the `comm` parameter is `None` or a standard `paradigm-client.communicator.Communicator`:
>   Raises an assertion error if there is no `PARADIGM_API_KEY` env variable or no given `api_key` value.
> * If the `comm` parameter is of type `paradigm-client.communicator.SagemakerCommunicator`:
>   Do not check for an api key.

Sounds good

**Comment by famoreau** [comment]
Modification done, test is passing.

**Pull request merged**
